databases:
  - name: budget_app
    databaseName: budget_app_jlqu
    user: budget_app_jlqu_user

services:
  - type: web
    name: Budget App
    env: ruby
    buildCommand: './render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_jlqu
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
